### ISSUE TITLE
pytest issues

### ISSUE THREAD

**Issue by dfateyev** [python-llfuse/python-llfuse#35] opened 2020-10-11 20:11 UTC
pytest has failed with the latest (1.3.8) version:
```
+ py.test-3 -v test
============================= test session starts ==============================
platform linux -- Python 3.9.0, pytest-6.0.2, py-1.9.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /builddir/build/BUILD/llfuse-1.3.8/test, configfile: pytest.ini
collecting ... collected 14 items
test/test_api.py::test_inquire_bits ERROR                                [  7%]
test/test_api.py::test_inquire_bits ERROR                                [  7%]
==================================== ERRORS ====================================
_____________________ ERROR at setup of test_inquire_bits ______________________
Traceback (most recent call last):
  File "/builddir/build/BUILD/llfuse-1.3.8/test/pytest_checklogs.py", line 135, in pytest_runtest_setup
    check_output(item)
  File "/builddir/build/BUILD/llfuse-1.3.8/test/pytest_checklogs.py", line 131, in check_output
    check_test_log(item.catch_log_handler)
AttributeError: 'Function' object has no attribute 'catch_log_handler'
____________________ ERROR at teardown of test_inquire_bits ____________________
Traceback (most recent call last):
  File "/builddir/build/BUILD/llfuse-1.3.8/test/pytest_checklogs.py", line 141, in pytest_runtest_teardown
    check_output(item)
  File "/builddir/build/BUILD/llfuse-1.3.8/test/pytest_checklogs.py", line 131, in check_output
    check_test_log(item.catch_log_handler)
AttributeError: 'Function' object has no attribute 'catch_log_handler'
=========================== short test summary info ============================
ERROR test/test_api.py::test_inquire_bits - AttributeError: 'Function' object...
ERROR test/test_api.py::test_inquire_bits - AttributeError: 'Function' object...
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 2 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
============================== 2 errors in 0.11s ===============================
```

**Comment by ThomasWaldmann** [comment] 2020-10-12 10:41
That's a pytest issue, try pytest < 6.0.

**Comment by ThomasWaldmann** [comment] 2020-10-12 10:42
Also, this is not special to 1.3.8, but likely there since long.

**Comment by ThomasWaldmann** [comment] 2020-10-12 10:44
See there: https://github.com/python-llfuse/python-llfuse/blob/master/test/travis-install.sh#L6

**Comment by dfateyev** [comment] 2020-10-12 11:05
> That's a pytest issue, try pytest < 6.0 (or was it < 5.0?).

That was 6.0.2, and unfortunately I cannot downgrade pytest version — since the version provided by the distribution (Fedora) is used. Will wait for the fix from pytest, or any other workaround.

**Comment by ThomasWaldmann** [comment] 2020-10-12 11:22
catch_log_handler was removed in pytest 6.0.0rc1 (and thus, was released as 6.0).

can you check whether pytest >= 6.0 and pytest-catchlog works?

**Comment by dfateyev** [comment] 2020-11-15 18:19
Now, I have `pytest-catchlog` installed, but seems there are discrepancies:
```
+ py.test-3 -v test
/usr/lib/python3.9/site-packages/_pytest/config/__init__.py:415: PytestConfigWarning: pytest-catchlog plugin has been merged into the core, please remove it from your requirements.
  warnings.warn(
============================================================================================================ test session starts =============================================================================================================
platform linux -- Python 3.9.0, pytest-6.0.2, py-1.9.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/mock/rpmbuild/BUILD/llfuse-1.3.8/test, configfile: pytest.ini
plugins: catchlog-1.2.2
collected 14 items                                                                                                                                                                                                                           

test/test_api.py::test_inquire_bits ERROR                                                                                                                                                                                              [  7%]
test/test_api.py::test_inquire_bits ERROR                                                                                                                                                                                              [  7%]

=================================================================================================================== ERRORS ===================================================================================================================
____________________________________________________________________________________________________ ERROR at setup of test_inquire_bits _____________________________________________________________________________________________________
Traceback (most recent call last):
  File "/home/mock/rpmbuild/BUILD/llfuse-1.3.8/test/pytest_checklogs.py", line 135, in pytest_runtest_setup
    check_output(item)
  File "/home/mock/rpmbuild/BUILD/llfuse-1.3.8/test/pytest_checklogs.py", line 131, in check_output
    check_test_log(item.catch_log_handler)
AttributeError: 'Function' object has no attribute 'catch_log_handler'
___________________________________________________________________________________________________ ERROR at teardown of test_inquire_bits ___________________________________________________________________________________________________
Traceback (most recent call last):
  File "/home/mock/rpmbuild/BUILD/llfuse-1.3.8/test/pytest_checklogs.py", line 141, in pytest_runtest_teardown
    check_output(item)
  File "/home/mock/rpmbuild/BUILD/llfuse-1.3.8/test/pytest_checklogs.py", line 131, in check_output
    check_test_log(item.catch_log_handler)
AttributeError: 'Function' object has no attribute 'catch_log_handler'
============================================================================================================== warnings summary ==============================================================================================================
test/util.py:67
test/util.py:67
  /home/mock/rpmbuild/BUILD/llfuse-1.3.8/test/util.py:67: PytestUnknownMarkWarning: Unknown pytest.mark.uses_fuse - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    return pytest.mark.uses_fuse()

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================================================== short test summary info ===========================================================================================================
ERROR test/test_api.py::test_inquire_bits - AttributeError: 'Function' object has no attribute 'catch_log_handler'
ERROR test/test_api.py::test_inquire_bits - AttributeError: 'Function' object has no attribute 'catch_log_handler'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 2 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================================================================================= 2 warnings, 2 errors in 0.94s ========================================================================================================
error: Bad exit status from /var/tmp/rpm-tmp.sOJiwt (%check)
```

**Comment by ThomasWaldmann** [comment] 2020-11-16 17:29
https://github.com/libfuse/pyfuse3/issues/27 same there.

**Comment by ThomasWaldmann** [comment] 2020-11-16 17:46
OK, I can confirm the issue.

Maybe @Nikratio can fix this, it seems to be an issue in multiple of his projects (s3ql, pyfuse3 and also llfuse).

**Comment by ThomasWaldmann** [comment] 2020-11-27 16:19
https://github.com/libfuse/pyfuse3/commit/0070eddfc33fc2fba8eb4fe9353a2d2fa1ae575b
https://github.com/libfuse/pyfuse3/commit/ee1c57e919f1697a8dd980f28fd28c07615097ca

https://github.com/libfuse/pyfuse3/commit/d3df2433ae3f75a25e9626a0db8f398719b742f9 check this also

**Comment by ThomasWaldmann** [comment] 2020-12-04 19:34
Looks like all was ported to here also, thanks @Nikratio !

**Closed by ThomasWaldmann** 2020-12-04 19:34 UTC

**Comment by dfateyev** [comment] 2020-12-04 20:04
@ThomasWaldmann should a new formal release (covering this issue) be prepared?

**Comment by ThomasWaldmann** [comment] 2020-12-04 20:57
@dfateyev I'll do a 1.3.9 release after the current WIP fixes are in.

not sure I'll fix #42 though.

**Comment by dfateyev** [comment] 2021-01-21 17:49
@ThomasWaldmann sorry for being noisy, but are there any plans for the release?
The thing is that the build issue blocks package provision to the distributions with newer Python and/or pytest.

As I see, in Fedora the package "borgbackup" still depends on "llfuse", so dropping llfuse support will lead to "borgbackup" removal.
```
# repoquery -q --whatrequires python3-llfuse
borgbackup-0:1.1.13-2.fc33.x86_64
borgbackup-0:1.1.15-1.fc33.x86_64
```

**Comment by ThomasWaldmann** [comment] 2021-01-21 20:07
@dfateyev as we dropped py34 here, I guess we'll skil 1.3.9 release and go straight to 1.4.0.

There are still a few issues open for that milestone, see:

https://github.com/python-llfuse/python-llfuse/milestone/2
